-- Create the 'profiles' table to store user profile information, extending the default 'users' table from Supabase.
create table profiles
(
    id              uuid references auth.users on delete cascade not null primary key,
    updated_at      timestamp with time zone,
    username        text unique,
    full_name       text,
    avatar_url      text,
    account_balance numeric default 0,
    constraint username_length check (char_length(username) >= 3)
);

-- Create the 'groups' table to store information about investment groups.
create table groups
(
    id                      bigint generated by default as identity primary key,
    group_type              text                                         not null,
    created_at              timestamp with time zone default now()       not null,
    updated_at              timestamp with time zone,
    name                    text                                         not null unique,
    description             text,
    avatar_url              text,
    owner_id                uuid references auth.users on delete cascade not null,
    balance                 numeric                  default 0,
    contributions_finalized boolean                  default false,
    constraint name_length check (char_length(name) >= 1)
);


-- Create the 'group_roles' table to store the roles available to group members
create table group_roles
(
    id          bigint generated by default as identity primary key,
    name        text not null unique,
    description text
);

-- Create the 'group_members' table to manage group memberships.
create table group_members
(
    id        bigint generated by default as identity primary key,
    group_id  bigint references groups (id) on delete cascade not null,
    user_id   uuid references auth.users on delete cascade    not null,
    joined_at timestamp with time zone default now()          not null
);

-- Create the 'group_member_roles' table to manage the roles of group members.
create table group_member_roles
(
    id              bigint generated by default as identity primary key,
    group_member_id bigint references group_members (id) on delete cascade not null,
    role_id         bigint references group_roles (id) on delete cascade   not null
);

-- Create the 'contributions' table to track member contributions.
create table contributions
(
    id             bigint generated by default as identity primary key,
    group_id       bigint references groups (id) on delete cascade not null,
    user_id        uuid references auth.users on delete cascade    not null,
    amount         numeric                                         not null,
    contributed_at timestamp with time zone default now()          not null
);

-- Create the 'interest_rates' table to store interest rates based on group type.
create table interest_rates
(
    id         bigint generated by default as identity primary key,
    group_type text                                   not null unique,
    rate       numeric                                not null,
    updated_at timestamp with time zone default now() not null
);

-- Create the 'bonuses' table to store bonus amounts for groups.
create table bonuses
(
    id         bigint generated by default as identity primary key,
    group_id   bigint references groups (id) on delete cascade not null,
    amount     numeric                                         not null,
    created_at timestamp with time zone default now()          not null
);


----------------------- POLICIES -----------------------------------------------


-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles
    enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
    for select using (true);

create policy "Users can insert their own profile." on profiles
    for insert with check (auth.uid() = id);

create policy "Users can update own profile." on profiles
    for update using (auth.uid() = id);


alter table groups
    enable row level security;

-- group owner can update the group
create policy "Group owners can update own groups." on groups
    for update using (auth.uid() = owner_id);

-- group owner can delete the group
create policy "Group owners can delete own groups." on groups
    for delete using (auth.uid() = owner_id);



alter table group_roles
    enable row level security;

-- anyone can view group roles
create policy "Group roles are viewable by everyone." on group_roles
    for select using (true);

-- only service_role can insert group roles
create policy "Service role can insert group roles." on group_roles
    for insert with check (auth.role() = 'service_role');


alter table group_members
    enable row level security;

-- users can view their group memberships
create policy "Users can view their group memberships." on group_members
    for select using (auth.uid() = user_id);


-- group owner can add members
create policy "Group owners can add members." on group_members
    for insert with check (
    auth.uid() = (select owner_id
                  from groups
                  where id = group_id)
    );

-- group owner and admins can remove a member
create policy "Group owners and admins can remove members." on group_members
    for delete using (
    auth.uid() = (select owner_id
                  from groups
                  where id = group_id) or
    exists (select 1
            from group_member_roles
            where group_member_id = id
              and role_id = (select id from group_roles where name = 'admin'))
    );

-- group members can view group members
create policy "Group members can view group members." on group_members
    for select using (
    exists (select 1
            from group_members gm
            where gm.group_id = group_id
              and gm.user_id = auth.uid())
    );



alter table group_member_roles
    enable row level security;

-- group members can view their roles
create policy "Group members can view their roles." on group_member_roles
    for select using (
    exists (select 1
            from group_members
            where id = group_member_id
              and user_id = auth.uid())
    );

-- group owners can add roles to group members
create policy "Group owners can add roles to group members." on group_member_roles
    for insert with check (
    auth.uid() = (select owner_id
                  from groups
                  where id = (select group_id
                              from group_members
                              where id = group_member_id))
    );

-- group owner and admins can remove a role from a member
create policy "Group owners and admins can remove a role from a member." on group_member_roles
    for delete using (
    auth.uid() = (select owner_id
                  from groups
                  where id = (select group_id
                              from group_members
                              where id = group_member_id)) or exists (select 1
                                                                      from group_member_roles
                                                                      where group_member_id = id
                                                                        and role_id = (select id from group_roles where name = 'admin'))
    );



alter table contributions
    enable row level security;

-- group members can view their contributions
create policy "Group members can view their contributions." on contributions
    for select using (
    auth.uid() = user_id and
    exists (select 1
            from group_members
            where group_id = group_id
              and user_id = auth.uid())
    );

-- group members can add contributions, if group is not finalized
create policy "Group members can add contributions." on contributions
    for insert with check (
    (select contributions_finalized
     from groups
     where id = group_id) = false and
    exists (select 1
            from group_members
            where group_id = group_id
              and user_id = auth.uid())
    );


alter table interest_rates
    enable row level security;

-- anyone can view interest rates
create policy "Interest rates are viewable by everyone." on interest_rates
    for select using (true);

-- only service_role can insert interest rates
create policy "Service role can insert interest rates." on interest_rates
    for insert with check (auth.role() = 'service_role');


alter table bonuses
    enable row level security;

-- group members can view their bonuses
create policy "Group members can view their bonuses." on bonuses
    for select using (
    exists (select 1
            from group_members
            where group_id = group_id
              and user_id = auth.uid())
    );

----------------------- END POLICIES -----------------------------------------------

